//! # Lesson 04: Remote Attestation
//!
//! ## What is Remote Attestation?
//!
//! Remote attestation allows a platform to prove to a remote party what software
//! is running. The flow:
//!
//! 1. **Verifier** sends a random nonce to the platform
//! 2. **Platform** measures its own state (PCR values, enclave measurements)
//! 3. **Platform** creates a signed "attestation quote" binding the nonce to measurements
//! 4. **Verifier** checks:
//!    - Signature is valid (came from a genuine TPM/enclave)
//!    - Nonce matches what was sent (prevents replay)
//!    - Measurements match expected values (known-good software)
//!
//! ## Types of Attestation
//!
//! | Type | What it proves | Mechanism |
//! |------|---------------|-----------|
//! | TPM-based | Boot chain integrity | PCR quote signed by TPM key |
//! | SGX-based | Enclave code identity | REPORT signed by CPU key |
//! | Software-based | Code hash | Signed hash of application |
//!
//! ## Attack: Replay Attack
//!
//! An attacker captures a valid attestation quote and replays it later.
//! Defense: always include a fresh nonce from the verifier in the quote.
//!
//! ## Attack: Fork/VM Replay
//!
//! An attacker snapshots a VM, runs malicious code, then restores the snapshot
//! and presents the old (good) attestation. Defense: include a monotonic counter
//! or timestamp in the attestation.

use ring::digest;
use ring::hmac;
use serde::{Deserialize, Serialize};

/// A platform's identity — represents a TPM or enclave.
#[derive(Debug, Clone)]
pub struct PlatformIdentity {
    /// Platform's attestation key (HMAC key in this simulation).
    pub attestation_key: Vec<u8>,
    /// Current platform measurements (simulated PCR values).
    pub measurements: Vec<Vec<u8>>,
}

impl PlatformIdentity {
    /// Exercise 1: Create a new platform identity.
    ///
    /// Generate a random 32-byte attestation key and initialize measurements
    /// from the provided code hashes. Each measurement is a SHA-256 of a boot stage.
    ///
    /// Hints:
    /// - Use `ring::rand::SystemRandom` to generate the attestation key
    /// - Store the measurements as provided
    pub fn new(initial_measurements: Vec<Vec<u8>>) -> Self {
        todo!("Create platform identity with attestation key and measurements")
    }

    /// Exercise 2: Extend the platform measurements with a new value.
    ///
    /// Simulates TPM PCR extension: new_measurement = SHA-256(old || new)
    pub fn extend_measurement(&mut self, index: usize, measurement: &[u8]) {
        todo!("Extend platform measurement with new value")
    }

    /// Exercise 3: Generate an attestation quote.
    ///
    /// The quote binds a nonce to the current platform state:
    /// signature = HMAC-SHA256(attestation_key, nonce || all_measurements_concatenated)
    ///
    /// Returns an AttestationQuote containing the nonce, measurements, and signature.
    ///
    /// Hints:
    /// - Concatenate nonce + all measurements
    /// - Compute HMAC-SHA256 over the concatenation
    pub fn generate_quote(&self, nonce: &[u8]) -> AttestationQuote {
        todo!("Generate signed attestation quote")
    }
}

/// An attestation quote — proves platform state to a verifier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttestationQuote {
    /// The nonce from the verifier.
    pub nonce: Vec<u8>,
    /// Platform measurements at quote time.
    pub measurements: Vec<Vec<u8>>,
    /// HMAC signature over (nonce || measurements).
    pub signature: Vec<u8>,
}

/// A verifier that checks attestation quotes.
#[derive(Debug)]
pub struct AttestationVerifier {
    /// The expected platform measurements (known-good state).
    pub expected_measurements: Vec<Vec<u8>>,
    /// The platform's attestation public key (in simulation, the HMAC key).
    pub platform_key: Vec<u8>,
    /// Nonces that have been used (to prevent replay).
    used_nonces: Vec<Vec<u8>>,
}

impl AttestationVerifier {
    /// Exercise 4: Create a new verifier.
    pub fn new(expected_measurements: Vec<Vec<u8>>, platform_key: Vec<u8>) -> Self {
        todo!("Create attestation verifier")
    }

    /// Exercise 5: Generate a challenge nonce.
    ///
    /// The nonce should be a random 32-byte value.
    pub fn generate_nonce(&mut self) -> Vec<u8> {
        todo!("Generate random challenge nonce")
    }

    /// Exercise 6: Verify an attestation quote.
    ///
    /// Checks:
    /// 1. The nonce was previously generated by this verifier (anti-replay)
    /// 2. The signature is valid (HMAC matches the platform's key)
    /// 3. The measurements match the expected values
    ///
    /// Returns a VerificationResult indicating success or specific failure.
    ///
    /// Hints:
    /// - Check nonce exists in used_nonces
    /// - Recompute HMAC and compare with constant-time comparison
    /// - Compare measurements byte-by-byte
    pub fn verify_quote(&mut self, quote: &AttestationQuote) -> VerificationResult {
        todo!("Verify attestation quote (nonce, signature, measurements)")
    }
}

/// Result of attestation verification.
#[derive(Debug, Clone, PartialEq)]
pub enum VerificationResult {
    /// Attestation passed — platform is in expected state.
    Trusted,
    /// Nonce was not generated by this verifier or was already used.
    InvalidNonce,
    /// Signature does not match the platform's key.
    InvalidSignature,
    /// Measurements do not match expected values.
    MeasurementsMismatch,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_measurements() -> Vec<Vec<u8>> {
        vec![
            digest::digest(&digest::SHA256, b"BIOS").as_ref().to_vec(),
            digest::digest(&digest::SHA256, b"Bootloader").as_ref().to_vec(),
            digest::digest(&digest::SHA256, b"OS Kernel").as_ref().to_vec(),
        ]
    }

    #[test]
    fn test_platform_creation() {
        let measurements = make_measurements();
        let platform = PlatformIdentity::new(measurements.clone());
        assert_eq!(platform.attestation_key.len(), 32);
        assert_eq!(platform.measurements.len(), 3);
    }

    #[test]
    fn test_quote_contains_nonce() {
        let platform = PlatformIdentity::new(make_measurements());
        let nonce = b"challenge-123";
        let quote = platform.generate_quote(nonce);
        assert_eq!(quote.nonce, nonce);
    }

    #[test]
    fn test_quote_signature_deterministic() {
        let platform = PlatformIdentity::new(make_measurements());
        let nonce = b"test-nonce";
        let q1 = platform.generate_quote(nonce);
        let q2 = platform.generate_quote(nonce);
        assert_eq!(q1.signature, q2.signature);
    }

    #[test]
    fn test_attestation_success() {
        let measurements = make_measurements();
        let platform = PlatformIdentity::new(measurements.clone());
        let mut verifier = AttestationVerifier::new(measurements, platform.attestation_key.clone());

        let nonce = verifier.generate_nonce();
        let quote = platform.generate_quote(&nonce);

        let result = verifier.verify_quote(&quote);
        assert_eq!(result, VerificationResult::Trusted);
    }

    #[test]
    fn test_attestation_replay_rejected() {
        let measurements = make_measurements();
        let platform = PlatformIdentity::new(measurements.clone());
        let mut verifier = AttestationVerifier::new(measurements, platform.attestation_key.clone());

        let nonce = verifier.generate_nonce();
        let quote = platform.generate_quote(&nonce);

        // First verification succeeds
        assert_eq!(verifier.verify_quote(&quote), VerificationResult::Trusted);

        // Replay — same quote should fail (nonce already used)
        let result = verifier.verify_quote(&quote);
        assert_eq!(result, VerificationResult::InvalidNonce);
    }

    #[test]
    fn test_attestation_tampered_measurements() {
        let measurements = make_measurements();
        let mut platform = PlatformIdentity::new(measurements.clone());
        let mut verifier = AttestationVerifier::new(measurements, platform.attestation_key.clone());

        let nonce = verifier.generate_nonce();
        let mut quote = platform.generate_quote(&nonce);

        // Tamper with measurements after quote
        quote.measurements[0] = digest::digest(&digest::SHA256, b"MALWARE").as_ref().to_vec();

        let result = verifier.verify_quote(&quote);
        assert_ne!(result, VerificationResult::Trusted);
    }

    #[test]
    fn test_attestation_wrong_key() {
        let measurements = make_measurements();
        let platform = PlatformIdentity::new(measurements.clone());

        // Verifier has a different key
        let wrong_key = vec![0u8; 32];
        let mut verifier = AttestationVerifier::new(measurements, wrong_key);

        let nonce = verifier.generate_nonce();
        let quote = platform.generate_quote(&nonce);

        let result = verifier.verify_quote(&quote);
        assert_eq!(result, VerificationResult::InvalidSignature);
    }

    #[test]
    fn test_measurement_extension_changes_quote() {
        let measurements = make_measurements();
        let mut platform = PlatformIdentity::new(measurements.clone());
        let nonce = b"test";
        let q1 = platform.generate_quote(nonce);

        platform.extend_measurement(0, b"new stage");
        let q2 = platform.generate_quote(nonce);

        assert_ne!(q1.signature, q2.signature, "Quote should change after measurement extension");
    }
}
