//! # Lesson 01: Key Generation — Identity and Ephemeral Keypairs
//!
//! ## What Are We Building?
//!
//! Every secure messenger needs two types of keys:
//! - **Identity keys (Ed25519)**: Long-term signing keys that represent a user's identity.
//!   Used to authenticate key exchanges and sign prekey bundles.
//! - **Ephemeral keys (X25519)**: Short-term Diffie-Hellman keys used once per session.
//!   Provide forward secrecy — if compromised, past sessions remain secure.
//!
//! ## Ed25519 vs X25519
//!
//! | Property | Ed25519 | X25519 |
//! |----------|---------|--------|
//! | Purpose | Digital signatures | Key agreement (DH) |
//! | Key size | 32 bytes | 32 bytes |
//! | Signature size | 64 bytes | N/A |
//! | Security level | ~128-bit | ~128-bit |
//! | Use in Signal | Identity key, signed prekey signature | DH computations in X3DH |
//!
//! ## Attack: Key Reuse
//!
//! Reusing ephemeral keys destroys forward secrecy. If an attacker compromises a reused
//! ephemeral key, they can decrypt all sessions that used it. **Defense**: Generate a
//! fresh ephemeral keypair for every new session and zeroize after use.
//!
//! ## Attack: Weak Randomness
//!
//! If the RNG is predictable, an attacker can predict all generated keys.
//! **Defense**: Use OS-provided entropy (`rand::rngs::OsRng`) and never seed with
//! low-entropy sources like timestamps alone.

use ed25519_dalek::{SigningKey as Ed25519SigningKey, VerifyingKey as Ed25519VerifyingKey, Signature, Signer, Verifier};
use x25519_dalek::{EphemeralSecret, PublicKey as X25519PublicKey, StaticSecret};
use rand::rngs::OsRng;
use sha2::{Sha256, Digest};
use zeroize::Zeroize;

/// A complete identity for a messenger user.
///
/// Contains an Ed25519 signing key (identity) and can derive
/// X25519 ephemeral keys for key exchange.
#[derive(Clone)]
pub struct Identity {
    /// The long-term Ed25519 signing key.
    pub signing_key: Ed25519SigningKey,
}

impl Identity {
    /// Exercise 1: Generate a new random identity.
    ///
    /// Create an Ed25519 keypair using OS randomness.
    ///
    /// Hints:
    /// - Use `Ed25519SigningKey::generate(&mut OsRng)`
    /// - `OsRng` provides cryptographically secure random bytes from the OS
    pub fn generate() -> Self {
        todo!("Generate a new Ed25519 identity keypair")
    }

    /// Exercise 2: Get the verifying (public) key from this identity.
    ///
    /// Returns the Ed25519VerifyingKey corresponding to the signing key.
    ///
    /// Hints:
    /// - Use `self.signing_key.verifying_key()`
    pub fn verifying_key(&self) -> Ed25519VerifyingKey {
        todo!("Return the public verifying key")
    }

    /// Exercise 3: Sign a message with this identity's signing key.
    ///
    /// Returns the 64-byte Ed25519 signature.
    ///
    /// Hints:
    /// - Use `self.signing_key.sign(message)`
    /// - The Signer trait provides the `.sign()` method
    pub fn sign(&self, message: &[u8]) -> Signature {
        todo!("Sign the message with Ed25519")
    }

    /// Exercise 4: Verify a signature against this identity's public key.
    ///
    /// Returns true if the signature is valid for the given message.
    ///
    /// Hints:
    /// - Use `self.verifying_key().verify(message, &signature)`
    /// - Returns Ok(()) on success, Err on failure
    pub fn verify(&self, message: &[u8], signature: &Signature) -> bool {
        todo!("Verify an Ed25519 signature")
    }

    /// Exercise 5: Generate an ephemeral X25519 keypair for key exchange.
    ///
    /// Returns (secret, public) where:
    /// - secret: EphemeralSecret (must be used exactly once)
    /// - public: X25519PublicKey to send to the other party
    ///
    /// Hints:
    /// - Use `EphemeralSecret::random_from_rng(OsRng)`
    /// - Derive the public key with `X25519PublicKey::from(&secret)`
    pub fn generate_ephemeral() -> (EphemeralSecret, X25519PublicKey) {
        todo!("Generate an ephemeral X25519 keypair")
    }

    /// Exercise 6: Generate a "signed prekey" — an X25519 keypair signed by the identity.
    ///
    /// Returns (secret, public, signature) where:
    /// - secret: StaticSecret (persists across sessions until rotated)
    /// - public: X25519PublicKey
    /// - signature: Ed25519 signature over the public key bytes
    ///
    /// This is used in X3DH: the signed prekey is published on a server,
    /// and the signature proves it was generated by the identity owner.
    ///
    /// Hints:
    /// - Generate a StaticSecret with `StaticSecret::random_from_rng(OsRng)`
    /// - Derive public key with `X25519PublicKey::from(&secret)`
    /// - Sign the public key bytes: `self.signing_key.sign(public.as_bytes())`
    pub fn generate_signed_prekey(&self) -> (StaticSecret, X25519PublicKey, Signature) {
        todo!("Generate a signed prekey (X25519 + Ed25519 signature)")
    }
}

/// Exercise 7: Derive a fingerprint from an Ed25519 verifying key.
///
/// Compute SHA-256 of the public key bytes and return the 32-byte hash.
/// This is used for key verification / safety numbers.
///
/// Hints:
/// - Create a `Sha256` hasher
/// - Feed the verifying key bytes: `key.as_bytes()`
/// - Finalize and return the hash bytes
pub fn fingerprint(key: &Ed25519VerifyingKey) -> [u8; 32] {
    todo!("Compute SHA-256 fingerprint of a public key")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_identity_generate() {
        let identity = Identity::generate();
        // Just verify it doesn't panic and produces a valid key
        let _vk = identity.verifying_key();
    }

    #[test]
    fn test_sign_and_verify() {
        let identity = Identity::generate();
        let message = b"Hello, secure world!";
        let signature = identity.sign(message);
        assert!(identity.verify(message, &signature), "Valid signature should verify");
    }

    #[test]
    fn test_verify_wrong_message() {
        let identity = Identity::generate();
        let message = b"Original message";
        let signature = identity.sign(message);
        let tampered = b"Tampered message";
        assert!(!identity.verify(tampered, &signature), "Signature on wrong message should fail");
    }

    #[test]
    fn test_verify_wrong_key() {
        let alice = Identity::generate();
        let bob = Identity::generate();
        let message = b"Hello from Alice";
        let signature = alice.sign(message);
        // Bob's key should not verify Alice's signature
        // We need to manually check: use Bob's verifying key with Alice's signature
        assert!(
            bob.verifying_key().verify(message, &signature).is_err(),
            "Wrong key should not verify signature"
        );
    }

    #[test]
    fn test_ephemeral_keypair() {
        let (secret, public) = Identity::generate_ephemeral();
        // Verify we can do DH with it
        let (secret2, public2) = Identity::generate_ephemeral();
        let shared1 = secret.diffie_hellman(&public2);
        let shared2 = secret2.diffie_hellman(&public);
        assert_eq!(shared1.as_bytes(), shared2.as_bytes(), "DH should produce same shared secret");
    }

    #[test]
    fn test_signed_prekey_signature() {
        let identity = Identity::generate();
        let (_secret, public, signature) = identity.generate_signed_prekey();
        // The signature should be over the public key bytes
        assert!(
            identity.verify(public.as_bytes(), &signature),
            "Signed prekey signature should be valid"
        );
    }

    #[test]
    fn test_fingerprint_deterministic() {
        let identity = Identity::generate();
        let fp1 = fingerprint(&identity.verifying_key());
        let fp2 = fingerprint(&identity.verifying_key());
        assert_eq!(fp1, fp2, "Fingerprint should be deterministic");
    }

    #[test]
    fn test_fingerprint_different_keys() {
        let alice = Identity::generate();
        let bob = Identity::generate();
        let fp_alice = fingerprint(&alice.verifying_key());
        let fp_bob = fingerprint(&bob.verifying_key());
        assert_ne!(fp_alice, fp_bob, "Different keys should have different fingerprints");
    }
}
