#[cfg(not(feature = "solution"))]
pub mod p01_max_subarray;
#[cfg(feature = "solution")]
#[path = "solution/p01_max_subarray.rs"]
pub mod p01_max_subarray;
#[cfg(not(feature = "solution"))]
pub mod p02_jump_game;
#[cfg(feature = "solution")]
#[path = "solution/p02_jump_game.rs"]
pub mod p02_jump_game;
#[cfg(not(feature = "solution"))]
pub mod p03_jump_game_ii;
#[cfg(feature = "solution")]
#[path = "solution/p03_jump_game_ii.rs"]
pub mod p03_jump_game_ii;
#[cfg(not(feature = "solution"))]
pub mod p04_gas_station;
#[cfg(feature = "solution")]
#[path = "solution/p04_gas_station.rs"]
pub mod p04_gas_station;
#[cfg(not(feature = "solution"))]
pub mod p05_hand_of_straights;
#[cfg(feature = "solution")]
#[path = "solution/p05_hand_of_straights.rs"]
pub mod p05_hand_of_straights;
#[cfg(not(feature = "solution"))]
pub mod p06_merge_triplets;
#[cfg(feature = "solution")]
#[path = "solution/p06_merge_triplets.rs"]
pub mod p06_merge_triplets;
#[cfg(not(feature = "solution"))]
pub mod p07_partition_labels;
#[cfg(feature = "solution")]
#[path = "solution/p07_partition_labels.rs"]
pub mod p07_partition_labels;
#[cfg(not(feature = "solution"))]
pub mod p08_valid_parenthesis_string;
#[cfg(feature = "solution")]
#[path = "solution/p08_valid_parenthesis_string.rs"]
pub mod p08_valid_parenthesis_string;
