#[cfg(not(feature = "solution"))]
pub mod p01_climbing_stairs;
#[cfg(feature = "solution")]
#[path = "solution/p01_climbing_stairs.rs"]
pub mod p01_climbing_stairs;
#[cfg(not(feature = "solution"))]
pub mod p02_house_robber;
#[cfg(feature = "solution")]
#[path = "solution/p02_house_robber.rs"]
pub mod p02_house_robber;
#[cfg(not(feature = "solution"))]
pub mod p03_house_robber_ii;
#[cfg(feature = "solution")]
#[path = "solution/p03_house_robber_ii.rs"]
pub mod p03_house_robber_ii;
#[cfg(not(feature = "solution"))]
pub mod p04_coin_change;
#[cfg(feature = "solution")]
#[path = "solution/p04_coin_change.rs"]
pub mod p04_coin_change;
#[cfg(not(feature = "solution"))]
pub mod p05_longest_increasing_subseq;
#[cfg(feature = "solution")]
#[path = "solution/p05_longest_increasing_subseq.rs"]
pub mod p05_longest_increasing_subseq;
#[cfg(not(feature = "solution"))]
pub mod p06_longest_common_subseq;
#[cfg(feature = "solution")]
#[path = "solution/p06_longest_common_subseq.rs"]
pub mod p06_longest_common_subseq;
#[cfg(not(feature = "solution"))]
pub mod p07_edit_distance;
#[cfg(feature = "solution")]
#[path = "solution/p07_edit_distance.rs"]
pub mod p07_edit_distance;
#[cfg(not(feature = "solution"))]
pub mod p08_partition_equal_subset;
#[cfg(feature = "solution")]
#[path = "solution/p08_partition_equal_subset.rs"]
pub mod p08_partition_equal_subset;
#[cfg(not(feature = "solution"))]
pub mod p09_unique_paths;
#[cfg(feature = "solution")]
#[path = "solution/p09_unique_paths.rs"]
pub mod p09_unique_paths;
#[cfg(not(feature = "solution"))]
pub mod p10_word_break;
#[cfg(feature = "solution")]
#[path = "solution/p10_word_break.rs"]
pub mod p10_word_break;
#[cfg(not(feature = "solution"))]
pub mod p11_longest_palindromic_sub;
#[cfg(feature = "solution")]
#[path = "solution/p11_longest_palindromic_sub.rs"]
pub mod p11_longest_palindromic_sub;
#[cfg(not(feature = "solution"))]
pub mod p12_decode_ways;
#[cfg(feature = "solution")]
#[path = "solution/p12_decode_ways.rs"]
pub mod p12_decode_ways;
