#[cfg(not(feature = "solution"))]
pub mod p01_insert_interval;
#[cfg(feature = "solution")]
#[path = "solution/p01_insert_interval.rs"]
pub mod p01_insert_interval;
#[cfg(not(feature = "solution"))]
pub mod p02_merge_intervals;
#[cfg(feature = "solution")]
#[path = "solution/p02_merge_intervals.rs"]
pub mod p02_merge_intervals;
#[cfg(not(feature = "solution"))]
pub mod p03_non_overlapping;
#[cfg(feature = "solution")]
#[path = "solution/p03_non_overlapping.rs"]
pub mod p03_non_overlapping;
#[cfg(not(feature = "solution"))]
pub mod p04_meeting_rooms;
#[cfg(feature = "solution")]
#[path = "solution/p04_meeting_rooms.rs"]
pub mod p04_meeting_rooms;
#[cfg(not(feature = "solution"))]
pub mod p05_meeting_rooms_ii;
#[cfg(feature = "solution")]
#[path = "solution/p05_meeting_rooms_ii.rs"]
pub mod p05_meeting_rooms_ii;
#[cfg(not(feature = "solution"))]
pub mod p06_min_interval_queries;
#[cfg(feature = "solution")]
#[path = "solution/p06_min_interval_queries.rs"]
pub mod p06_min_interval_queries;
