apiVersion: v1
kind: Service
metadata:
  name: flash-sale-api
  labels:
    app: flash-sale-api
spec:
  type: ClusterIP
  selector:
    app: flash-sale-api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
