pub mod tree_node;
#[cfg(not(feature = "solution"))]
pub mod p01_invert_tree;
#[cfg(feature = "solution")]
#[path = "solution/p01_invert_tree.rs"]
pub mod p01_invert_tree;
#[cfg(not(feature = "solution"))]
pub mod p02_max_depth;
#[cfg(feature = "solution")]
#[path = "solution/p02_max_depth.rs"]
pub mod p02_max_depth;
#[cfg(not(feature = "solution"))]
pub mod p03_diameter_binary_tree;
#[cfg(feature = "solution")]
#[path = "solution/p03_diameter_binary_tree.rs"]
pub mod p03_diameter_binary_tree;
#[cfg(not(feature = "solution"))]
pub mod p04_balanced_tree;
#[cfg(feature = "solution")]
#[path = "solution/p04_balanced_tree.rs"]
pub mod p04_balanced_tree;
#[cfg(not(feature = "solution"))]
pub mod p05_same_tree;
#[cfg(feature = "solution")]
#[path = "solution/p05_same_tree.rs"]
pub mod p05_same_tree;
#[cfg(not(feature = "solution"))]
pub mod p06_subtree_of_tree;
#[cfg(feature = "solution")]
#[path = "solution/p06_subtree_of_tree.rs"]
pub mod p06_subtree_of_tree;
#[cfg(not(feature = "solution"))]
pub mod p07_lowest_common_ancestor;
#[cfg(feature = "solution")]
#[path = "solution/p07_lowest_common_ancestor.rs"]
pub mod p07_lowest_common_ancestor;
#[cfg(not(feature = "solution"))]
pub mod p08_level_order_traversal;
#[cfg(feature = "solution")]
#[path = "solution/p08_level_order_traversal.rs"]
pub mod p08_level_order_traversal;
#[cfg(not(feature = "solution"))]
pub mod p09_validate_bst;
#[cfg(feature = "solution")]
#[path = "solution/p09_validate_bst.rs"]
pub mod p09_validate_bst;
#[cfg(not(feature = "solution"))]
pub mod p10_kth_smallest_bst;
#[cfg(feature = "solution")]
#[path = "solution/p10_kth_smallest_bst.rs"]
pub mod p10_kth_smallest_bst;
#[cfg(not(feature = "solution"))]
pub mod p11_build_tree_preorder_inorder;
#[cfg(feature = "solution")]
#[path = "solution/p11_build_tree_preorder_inorder.rs"]
pub mod p11_build_tree_preorder_inorder;
#[cfg(not(feature = "solution"))]
pub mod p12_serialize_deserialize;
#[cfg(feature = "solution")]
#[path = "solution/p12_serialize_deserialize.rs"]
pub mod p12_serialize_deserialize;
