#[cfg(not(feature = "solution"))]
pub mod p01_best_time_buy_sell;
#[cfg(feature = "solution")]
#[path = "solution/p01_best_time_buy_sell.rs"]
pub mod p01_best_time_buy_sell;
#[cfg(not(feature = "solution"))]
pub mod p02_longest_substring_no_repeat;
#[cfg(feature = "solution")]
#[path = "solution/p02_longest_substring_no_repeat.rs"]
pub mod p02_longest_substring_no_repeat;
#[cfg(not(feature = "solution"))]
pub mod p03_longest_replacement;
#[cfg(feature = "solution")]
#[path = "solution/p03_longest_replacement.rs"]
pub mod p03_longest_replacement;
#[cfg(not(feature = "solution"))]
pub mod p04_min_window_substring;
#[cfg(feature = "solution")]
#[path = "solution/p04_min_window_substring.rs"]
pub mod p04_min_window_substring;
#[cfg(not(feature = "solution"))]
pub mod p05_sliding_window_max;
#[cfg(feature = "solution")]
#[path = "solution/p05_sliding_window_max.rs"]
pub mod p05_sliding_window_max;
