//! # Build Scripts
//!
//! Build scripts (`build.rs`) run at compile time and can:
//! - Generate Rust code from data files
//! - Set `cfg` flags based on environment
//! - Link native C/C++ libraries
//! - Compile C/C++ code
//! - Read environment variables
//!
//! The build script communicates with cargo through `println!("cargo:...")` directives.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Demonstrates generating Rust code from data.
/// In a real build.rs, you'd write this to $OUT_DIR/generated.rs
pub fn generate_code_from_data(data: &[(String, i32)]) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs\n\n");
    code.push_str("pub fn get_value(key: &str) -> Option<i32> {\n");
    code.push_str("    match key {\n");

    for (key, value) in data {
        code.push_str(&format!("        \"{key}\" => Some({value}),\n"));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n\n");

    code.push_str("pub fn all_keys() -> &'static [&'static str] {\n");
    let keys: Vec<String> = data.iter().map(|(k, _)| format!("\"{k}\"")).collect();
    code.push_str(&format!("    &[{}]\n", keys.join(", ")));
    code.push_str("}\n");

    code
}

/// Demonstrates generating a version constant.
pub fn generate_version_info(version: &str, git_hash: &str, build_time: &str) -> String {
    format!(
        r#"// Auto-generated by build.rs
pub const VERSION: &str = "{version}";
pub const GIT_HASH: &str = "{git_hash}";
pub const BUILD_TIME: &str = "{build_time}";

pub fn full_version() -> String {{
    format!("{{}} ({{}} built at {{}})", VERSION, GIT_HASH, BUILD_TIME)
}}
"#
    )
}

/// Demonstrates generating cfg flags based on platform detection.
pub fn generate_platform_cfg() -> Vec<String> {
    let mut directives = Vec::new();

    // In a real build.rs, you'd detect the platform
    directives.push("cargo:rustc-cfg=has_std".to_string());
    directives.push("cargo:rustc-cfg=platform_linux".to_string());

    directives
}

/// Demonstrates the cargo directive format.
pub fn parse_cargo_directives(output: &str) -> Vec<(String, String)> {
    let mut directives = Vec::new();

    for line in output.lines() {
        if let Some(directive) = line.strip_prefix("cargo:") {
            if let Some((key, value)) = directive.split_once('=') {
                directives.push((key.trim().to_string(), value.trim().to_string()));
            }
        }
    }

    directives
}

/// Demonstrates generating code from a template.
pub fn generate_from_template(template: &str, replacements: &HashMap<&str, &str>) -> String {
    let mut result = template.to_string();
    for (key, value) in replacements {
        result = result.replace(&format!("{{{{{key}}}}}"), value);
    }
    result
}

/// Demonstrates generating a lookup table from a CSV-like input.
pub fn generate_lookup_table(name: &str, entries: &[(&str, &str)]) -> String {
    let mut code = String::new();
    code.push_str(&format!("pub static {name}: &[(&str, &str)] = &[\n"));

    for (key, value) in entries {
        code.push_str(&format!("    (\"{key}\", \"{value}\"),\n"));
    }

    code.push_str("];\n\n");

    code.push_str(&format!(
        "pub fn lookup_{name}(key: &str) -> Option<&'static str> {{\n"
    ));
    code.push_str(&format!(
        "    {name}.iter().find(|(k, _)| *k == key).map(|(_, v)| *v)\n"
    ));
    code.push_str("}\n");

    code
}

/// Demonstrates generating enum variants from external data.
pub fn generate_status_codes(codes: &[(u16, &str, &str)]) -> String {
    let mut code = String::new();
    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    code.push_str("pub enum StatusCode {\n");

    for (num, name, _desc) in codes {
        code.push_str(&format!("    {name} = {num},\n"));
    }

    code.push_str("}\n\n");

    code.push_str("impl StatusCode {\n");
    code.push_str("    pub fn from_u16(code: u16) -> Option<Self> {\n");
    code.push_str("        match code {\n");

    for (num, name, _desc) in codes {
        code.push_str(&format!("            {num} => Some(Self::{name}),\n"));
    }

    code.push_str("            _ => None,\n");
    code.push_str("        }\n");
    code.push_str("    }\n\n");

    code.push_str("    pub fn as_u16(&self) -> u16 {\n");
    code.push_str("        *self as u16\n");
    code.push_str("    }\n\n");

    code.push_str("    pub fn description(&self) -> &'static str {\n");
    code.push_str("        match self {\n");

    for (_num, name, desc) in codes {
        code.push_str(&format!("            Self::{name} => \"{desc}\",\n"));
    }

    code.push_str("        }\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    code
}

/// Demonstrates generating a const array from a file listing.
pub fn generate_file_list(files: &[&str]) -> String {
    let mut code = String::new();
    code.push_str("pub const EMBEDDED_FILES: &[(&str, &[u8])] = &[\n");

    for file in files {
        let var_name = file.replace(['.', '/', '-'], "_").to_uppercase();
        code.push_str(&format!(
            "    (\"{file}\", include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{file}\"))),\n"
        ));
    }

    code.push_str("];\n");
    code
}

/// Demonstrates the output directory management pattern.
pub fn get_out_dir() -> PathBuf {
    PathBuf::from(std::env::var("OUT_DIR").unwrap_or_else(|_| "/tmp/build_output".to_string()))
}

/// Demonstrates generating code with conditional features.
pub fn generate_with_features(features: &[&str]) -> String {
    let mut code = String::new();

    for feature in features {
        code.push_str(&format!("#[cfg(feature = \"{feature}\")]\n"));
        code.push_str(&format!("pub mod {feature}_support {{\n"));
        code.push_str(&format!(
            "    pub fn is_enabled() -> bool {{ true }}\n"
        ));
        code.push_str("}\n\n");
    }

    code.push_str("pub fn available_features() -> Vec<&'static str> {\n");
    code.push_str("    vec![\n");
    for feature in features {
        code.push_str(&format!(
            "        #[cfg(feature = \"{feature}\")]\n"
        ));
        code.push_str(&format!("        \"{feature}\",\n"));
    }
    code.push_str("    ]\n");
    code.push_str("}\n");

    code
}

/// Demonstrates generating test data.
pub fn generate_test_data(tests: &[(&str, &str, &str)]) -> String {
    let mut code = String::new();
    code.push_str("#[cfg(test)]\n");
    code.push_str("mod generated_tests {\n");
    code.push_str("    use super::*;\n\n");

    for (name, input, expected) in tests {
        code.push_str(&format!("    #[test]\n"));
        code.push_str(&format!("    fn test_{name}() {{\n"));
        code.push_str(&format!("        let input = {input};\n"));
        code.push_str(&format!("        let expected = {expected};\n"));
        code.push_str(&format!("        assert_eq!(process(input), expected);\n"));
        code.push_str(&format!("    }}\n\n"));
    }

    code.push_str("}\n");
    code
}

/// Demonstrates the `rerun-if-changed` pattern.
pub fn generate_rerun_directives(files: &[&str]) -> Vec<String> {
    files
        .iter()
        .map(|f| format!("cargo:rerun-if-changed={f}"))
        .collect()
}

/// Demonstrates linking native libraries.
pub fn generate_link_directives(libs: &[&str]) -> Vec<String> {
    libs.iter().map(|lib| format!("cargo:rustc-link-lib={lib}")).collect()
}

/// Demonstrates setting search paths.
pub fn generate_search_paths(paths: &[&str]) -> Vec<String> {
    paths
        .iter()
        .map(|p| format!("cargo:rustc-link-search=native={p}"))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_code_from_data() {
        let data = vec![
            ("max_retries".to_string(), 3),
            ("timeout_ms".to_string(), 5000),
        ];
        let code = generate_code_from_data(&data);
        assert!(code.contains("get_value"));
        assert!(code.contains("max_retries"));
        assert!(code.contains("timeout_ms"));
        assert!(code.contains("all_keys"));
    }

    #[test]
    fn test_generate_version_info() {
        let code = generate_version_info("1.0.0", "abc123", "2024-01-01");
        assert!(code.contains("1.0.0"));
        assert!(code.contains("abc123"));
        assert!(code.contains("2024-01-01"));
        assert!(code.contains("full_version"));
    }

    #[test]
    fn test_generate_platform_cfg() {
        let directives = generate_platform_cfg();
        assert!(directives.iter().any(|d| d.contains("has_std")));
        assert!(directives.iter().any(|d| d.contains("platform_linux")));
    }

    #[test]
    fn test_parse_cargo_directives() {
        let output = "cargo:rustc-cfg=feature_x\ncargo:rustc-link-lib=ssl";
        let directives = parse_cargo_directives(output);
        assert_eq!(directives.len(), 2);
        assert_eq!(directives[0].0, "rustc-cfg");
        assert_eq!(directives[0].1, "feature_x");
    }

    #[test]
    fn test_generate_from_template() {
        let mut replacements = HashMap::new();
        replacements.insert("NAME", "Server");
        replacements.insert("PORT", "8080");

        let template = "pub struct {{NAME}} { port: u16 } // port={{PORT}}";
        let result = generate_from_template(template, &replacements);
        assert!(result.contains("Server"));
        assert!(result.contains("8080"));
    }

    #[test]
    fn test_generate_lookup_table() {
        let entries = vec![("key1", "value1"), ("key2", "value2")];
        let code = generate_lookup_table("my_table", &entries);
        assert!(code.contains("my_table"));
        assert!(code.contains("key1"));
        assert!(code.contains("lookup_my_table"));
    }

    #[test]
    fn test_generate_status_codes() {
        let codes = vec![
            (200, "Ok", "Request succeeded"),
            (404, "NotFound", "Resource not found"),
        ];
        let code = generate_status_codes(&codes);
        assert!(code.contains("StatusCode"));
        assert!(code.contains("Ok"));
        assert!(code.contains("NotFound"));
        assert!(code.contains("from_u16"));
        assert!(code.contains("description"));
    }

    #[test]
    fn test_generate_file_list() {
        let files = vec!["config.json", "schema.sql"];
        let code = generate_file_list(&files);
        assert!(code.contains("EMBEDDED_FILES"));
        assert!(code.contains("config.json"));
        assert!(code.contains("include_bytes"));
    }

    #[test]
    fn test_generate_with_features() {
        let features = vec!["tls", "compression", "websocket"];
        let code = generate_with_features(&features);
        assert!(code.contains("tls_support"));
        assert!(code.contains("compression_support"));
        assert!(code.contains("available_features"));
    }

    #[test]
    fn test_generate_test_data() {
        let tests = vec![
            ("basic", "1 + 1", "2"),
            ("string", "\"hello\".len()", "5"),
        ];
        let code = generate_test_data(&tests);
        assert!(code.contains("test_basic"));
        assert!(code.contains("test_string"));
    }

    #[test]
    fn test_generate_rerun_directives() {
        let directives = generate_rerun_directives(&["build.rs", "data.txt"]);
        assert_eq!(directives.len(), 2);
        assert!(directives[0].contains("build.rs"));
        assert!(directives[1].contains("data.txt"));
    }

    #[test]
    fn test_generate_link_directives() {
        let directives = generate_link_directives(&["ssl", "crypto", "z"]);
        assert_eq!(directives.len(), 3);
        assert!(directives[0].contains("ssl"));
    }

    #[test]
    fn test_generate_search_paths() {
        let paths = generate_search_paths(&["/usr/lib", "/usr/local/lib"]);
        assert_eq!(paths.len(), 2);
        assert!(paths[0].contains("/usr/lib"));
    }

    #[test]
    fn test_get_out_dir() {
        let dir = get_out_dir();
        // Should return some path (either OUT_DIR or /tmp/build_output)
        assert!(!dir.to_str().unwrap().is_empty());
    }
}
