pub mod list_node;
#[cfg(not(feature = "solution"))]
pub mod p01_reverse_list;
#[cfg(feature = "solution")]
#[path = "solution/p01_reverse_list.rs"]
pub mod p01_reverse_list;
#[cfg(not(feature = "solution"))]
pub mod p02_merge_two_sorted;
#[cfg(feature = "solution")]
#[path = "solution/p02_merge_two_sorted.rs"]
pub mod p02_merge_two_sorted;
#[cfg(not(feature = "solution"))]
pub mod p03_linked_list_cycle;
#[cfg(feature = "solution")]
#[path = "solution/p03_linked_list_cycle.rs"]
pub mod p03_linked_list_cycle;
#[cfg(not(feature = "solution"))]
pub mod p04_remove_nth_from_end;
#[cfg(feature = "solution")]
#[path = "solution/p04_remove_nth_from_end.rs"]
pub mod p04_remove_nth_from_end;
#[cfg(not(feature = "solution"))]
pub mod p05_reorder_list;
#[cfg(feature = "solution")]
#[path = "solution/p05_reorder_list.rs"]
pub mod p05_reorder_list;
#[cfg(not(feature = "solution"))]
pub mod p06_add_two_numbers;
#[cfg(feature = "solution")]
#[path = "solution/p06_add_two_numbers.rs"]
pub mod p06_add_two_numbers;
#[cfg(not(feature = "solution"))]
pub mod p07_copy_random_pointer;
#[cfg(feature = "solution")]
#[path = "solution/p07_copy_random_pointer.rs"]
pub mod p07_copy_random_pointer;
