#[cfg(not(feature = "solution"))]
pub mod p01_two_sum;
#[cfg(feature = "solution")]
#[path = "solution/p01_two_sum.rs"]
pub mod p01_two_sum;
#[cfg(not(feature = "solution"))]
pub mod p02_contains_duplicate;
#[cfg(feature = "solution")]
#[path = "solution/p02_contains_duplicate.rs"]
pub mod p02_contains_duplicate;
#[cfg(not(feature = "solution"))]
pub mod p03_valid_anagram;
#[cfg(feature = "solution")]
#[path = "solution/p03_valid_anagram.rs"]
pub mod p03_valid_anagram;
#[cfg(not(feature = "solution"))]
pub mod p04_group_anagrams;
#[cfg(feature = "solution")]
#[path = "solution/p04_group_anagrams.rs"]
pub mod p04_group_anagrams;
#[cfg(not(feature = "solution"))]
pub mod p05_top_k_frequent;
#[cfg(feature = "solution")]
#[path = "solution/p05_top_k_frequent.rs"]
pub mod p05_top_k_frequent;
#[cfg(not(feature = "solution"))]
pub mod p06_product_except_self;
#[cfg(feature = "solution")]
#[path = "solution/p06_product_except_self.rs"]
pub mod p06_product_except_self;
#[cfg(not(feature = "solution"))]
pub mod p07_encode_decode_strings;
#[cfg(feature = "solution")]
#[path = "solution/p07_encode_decode_strings.rs"]
pub mod p07_encode_decode_strings;
#[cfg(not(feature = "solution"))]
pub mod p08_longest_consecutive;
#[cfg(feature = "solution")]
#[path = "solution/p08_longest_consecutive.rs"]
pub mod p08_longest_consecutive;
