#[cfg(not(feature = "solution"))]
pub mod p01_rotate_image;
#[cfg(feature = "solution")]
#[path = "solution/p01_rotate_image.rs"]
pub mod p01_rotate_image;
#[cfg(not(feature = "solution"))]
pub mod p02_spiral_matrix;
#[cfg(feature = "solution")]
#[path = "solution/p02_spiral_matrix.rs"]
pub mod p02_spiral_matrix;
#[cfg(not(feature = "solution"))]
pub mod p03_set_matrix_zeroes;
#[cfg(feature = "solution")]
#[path = "solution/p03_set_matrix_zeroes.rs"]
pub mod p03_set_matrix_zeroes;
#[cfg(not(feature = "solution"))]
pub mod p04_happy_number;
#[cfg(feature = "solution")]
#[path = "solution/p04_happy_number.rs"]
pub mod p04_happy_number;
#[cfg(not(feature = "solution"))]
pub mod p05_plus_one;
#[cfg(feature = "solution")]
#[path = "solution/p05_plus_one.rs"]
pub mod p05_plus_one;
#[cfg(not(feature = "solution"))]
pub mod p06_pow_x_n;
#[cfg(feature = "solution")]
#[path = "solution/p06_pow_x_n.rs"]
pub mod p06_pow_x_n;
#[cfg(not(feature = "solution"))]
pub mod p07_multiply_strings;
#[cfg(feature = "solution")]
#[path = "solution/p07_multiply_strings.rs"]
pub mod p07_multiply_strings;
#[cfg(not(feature = "solution"))]
pub mod p08_detect_squares;
#[cfg(feature = "solution")]
#[path = "solution/p08_detect_squares.rs"]
pub mod p08_detect_squares;
