#[cfg(not(feature = "solution"))]
pub mod p01_kth_largest_element;
#[cfg(feature = "solution")]
#[path = "solution/p01_kth_largest_element.rs"]
pub mod p01_kth_largest_element;
#[cfg(not(feature = "solution"))]
pub mod p02_last_stone_weight;
#[cfg(feature = "solution")]
#[path = "solution/p02_last_stone_weight.rs"]
pub mod p02_last_stone_weight;
#[cfg(not(feature = "solution"))]
pub mod p03_k_closest_points;
#[cfg(feature = "solution")]
#[path = "solution/p03_k_closest_points.rs"]
pub mod p03_k_closest_points;
#[cfg(not(feature = "solution"))]
pub mod p04_kth_largest_stream;
#[cfg(feature = "solution")]
#[path = "solution/p04_kth_largest_stream.rs"]
pub mod p04_kth_largest_stream;
#[cfg(not(feature = "solution"))]
pub mod p05_task_scheduler;
#[cfg(feature = "solution")]
#[path = "solution/p05_task_scheduler.rs"]
pub mod p05_task_scheduler;
#[cfg(not(feature = "solution"))]
pub mod p06_twitter;
#[cfg(feature = "solution")]
#[path = "solution/p06_twitter.rs"]
pub mod p06_twitter;
