#[cfg(not(feature = "solution"))]
pub mod p01_single_number;
#[cfg(feature = "solution")]
#[path = "solution/p01_single_number.rs"]
pub mod p01_single_number;
#[cfg(not(feature = "solution"))]
pub mod p02_number_of_1_bits;
#[cfg(feature = "solution")]
#[path = "solution/p02_number_of_1_bits.rs"]
pub mod p02_number_of_1_bits;
#[cfg(not(feature = "solution"))]
pub mod p03_counting_bits;
#[cfg(feature = "solution")]
#[path = "solution/p03_counting_bits.rs"]
pub mod p03_counting_bits;
#[cfg(not(feature = "solution"))]
pub mod p04_reverse_bits;
#[cfg(feature = "solution")]
#[path = "solution/p04_reverse_bits.rs"]
pub mod p04_reverse_bits;
#[cfg(not(feature = "solution"))]
pub mod p05_missing_number;
#[cfg(feature = "solution")]
#[path = "solution/p05_missing_number.rs"]
pub mod p05_missing_number;
#[cfg(not(feature = "solution"))]
pub mod p06_sum_two_integers;
#[cfg(feature = "solution")]
#[path = "solution/p06_sum_two_integers.rs"]
pub mod p06_sum_two_integers;
