#[cfg(not(feature = "solution"))]
pub mod p01_valid_parentheses;
#[cfg(feature = "solution")]
#[path = "solution/p01_valid_parentheses.rs"]
pub mod p01_valid_parentheses;
#[cfg(not(feature = "solution"))]
pub mod p02_min_stack;
#[cfg(feature = "solution")]
#[path = "solution/p02_min_stack.rs"]
pub mod p02_min_stack;
#[cfg(not(feature = "solution"))]
pub mod p03_eval_reverse_polish;
#[cfg(feature = "solution")]
#[path = "solution/p03_eval_reverse_polish.rs"]
pub mod p03_eval_reverse_polish;
#[cfg(not(feature = "solution"))]
pub mod p04_daily_temperatures;
#[cfg(feature = "solution")]
#[path = "solution/p04_daily_temperatures.rs"]
pub mod p04_daily_temperatures;
#[cfg(not(feature = "solution"))]
pub mod p05_car_fleet;
#[cfg(feature = "solution")]
#[path = "solution/p05_car_fleet.rs"]
pub mod p05_car_fleet;
#[cfg(not(feature = "solution"))]
pub mod p06_largest_rectangle;
#[cfg(feature = "solution")]
#[path = "solution/p06_largest_rectangle.rs"]
pub mod p06_largest_rectangle;
