#[cfg(not(feature = "solution"))]
pub mod p01_subsets;
#[cfg(feature = "solution")]
#[path = "solution/p01_subsets.rs"]
pub mod p01_subsets;
#[cfg(not(feature = "solution"))]
pub mod p02_combinations;
#[cfg(feature = "solution")]
#[path = "solution/p02_combinations.rs"]
pub mod p02_combinations;
#[cfg(not(feature = "solution"))]
pub mod p03_permutations;
#[cfg(feature = "solution")]
#[path = "solution/p03_permutations.rs"]
pub mod p03_permutations;
#[cfg(not(feature = "solution"))]
pub mod p04_subsets_ii;
#[cfg(feature = "solution")]
#[path = "solution/p04_subsets_ii.rs"]
pub mod p04_subsets_ii;
#[cfg(not(feature = "solution"))]
pub mod p05_combination_sum;
#[cfg(feature = "solution")]
#[path = "solution/p05_combination_sum.rs"]
pub mod p05_combination_sum;
#[cfg(not(feature = "solution"))]
pub mod p06_word_search;
#[cfg(feature = "solution")]
#[path = "solution/p06_word_search.rs"]
pub mod p06_word_search;
#[cfg(not(feature = "solution"))]
pub mod p07_palindrome_partitioning;
#[cfg(feature = "solution")]
#[path = "solution/p07_palindrome_partitioning.rs"]
pub mod p07_palindrome_partitioning;
#[cfg(not(feature = "solution"))]
pub mod p08_letter_combinations;
#[cfg(feature = "solution")]
#[path = "solution/p08_letter_combinations.rs"]
pub mod p08_letter_combinations;
#[cfg(not(feature = "solution"))]
pub mod p09_n_queens;
#[cfg(feature = "solution")]
#[path = "solution/p09_n_queens.rs"]
pub mod p09_n_queens;
