//! # Lesson 02: Lattice-Based Cryptography — Learning With Errors (LWE)
//!
//! ## What is a Lattice?
//!
//! A lattice is a regular grid of points in n-dimensional space, generated by a set
//! of basis vectors. Think of it as an n-dimensional generalization of a crystal
//! structure.
//!
//! ```
//! Lattice in 2D:
//!   *     *     *     *
//!
//!   *     *     *     *
//!
//!   *     *     *     *
//! ```
//!
//! ## The Hard Problems
//!
//! **Shortest Vector Problem (SVP)**: Given a lattice basis, find the shortest
//! non-zero vector. This is NP-hard for exact solutions and believed hard for
//! approximate solutions.
//!
//! **Learning With Errors (LWE)**: Given (A, b = A*s + e mod q), find the secret s.
//! The error vector e makes this hard — without e, it's just linear algebra.
//!
//! ## Why Lattices?
//!
//! 1. **Post-quantum security**: No known quantum algorithm efficiently solves SVP/LWE
//! 2. **Versatile**: Supports encryption, signatures, fully homomorphic encryption
//! 3. **Efficient**: Operations are matrix/vector arithmetic
//! 4. **Worst-case to average-case**: Breaking a random LWE instance implies solving
//!    SVP on ANY lattice (unprecedented hardness guarantee)
//!
//! ## Attack Demo: LWE with Tiny Parameters
//!
//! With small parameters (small n, small q, small error), LWE can be solved by
//! brute force or lattice reduction. This is why real PQC uses large parameters.

/// Exercise 1: Generate an LWE sample (a, b) where b = a * s + e mod q.
///
/// Given a secret scalar `s`, a public vector `a`, an error `e`, and modulus `q`,
/// compute b = (a * s + e) mod q.
///
/// This is the core LWE relation. The security comes from the fact that without
/// knowing e, it's hard to recover s from many (a, b) pairs.
///
/// Hints:
/// - Multiply each element of `a` by `s`, add corresponding `e`, reduce mod `q`
/// - All arithmetic is modular
pub fn lwe_sample(a: &[i64], s: i64, e: &[i64], q: i64) -> Vec<i64> {
    todo!("Compute LWE sample: b = a*s + e mod q")
}

/// Exercise 2: Check if a given (a, b) pair is a valid LWE sample for secret s.
///
/// Verify that b[i] = (a[i] * s + e[i]) mod q for some small error e[i].
/// The error is "small" if |e[i]| <= max_error.
///
/// Return true if the sample is valid (all errors are within bounds).
pub fn verify_lwe_sample(a: &[i64], b: &[i64], s: i64, q: i64, max_error: i64) -> bool {
    todo!("Verify LWE sample validity")
}

/// Exercise 3: Encrypt a single bit using a simplified LWE encryption scheme.
///
/// LWE Encryption (Regev-style):
/// - Public key: (A, b = A*s + e)
/// - To encrypt bit m (0 or 1):
///   1. Choose random subset r of {0,1}^n
///   2. u = A^T * r  (mod q)
///   3. v = b^T * r + m * floor(q/2)  (mod q)
/// - Ciphertext: (u, v)
///
/// For simplicity, we precompute u and v given the random subset indices.
///
/// Hints:
/// - `subset_indices` contains indices into the rows of `a_matrix` and `b`
/// - Sum the selected rows of a_matrix (transposed) to get u
/// - Sum the selected elements of b, then add m * (q/2) to get v
pub fn lwe_encrypt_bit(
    a_matrix: &[Vec<i64>],
    b: &[i64],
    subset_indices: &[usize],
    message_bit: u8,
    q: i64,
) -> (Vec<i64>, i64) {
    todo!("Encrypt a bit using LWE")
}

/// Exercise 4: Decrypt an LWE ciphertext to recover the message bit.
///
/// Given ciphertext (u, v) and secret s, compute:
///   noise = v - u . s  (mod q)
///
/// If |noise| < q/4, the bit is 0. Otherwise, it's 1.
///
/// Hints:
/// - Compute dot product of u and s, subtract from v, reduce mod q
/// - Center the result around 0 (handle negative modular arithmetic)
/// - Compare absolute value with q/4
pub fn lwe_decrypt_bit(u: &[i64], v: i64, s: &[i64], q: i64) -> u8 {
    todo!("Decrypt an LWE ciphertext bit")
}

/// Exercise 5: Compute the noise level of an LWE ciphertext.
///
/// The noise is: noise = v - u . s (mod q), centered around 0.
/// Return the absolute value of the centered noise.
///
/// This is useful for auditing — if the noise is too large, the ciphertext
/// may be corrupted or under attack.
pub fn lwe_noise_level(u: &[i64], v: i64, s: &[i64], q: i64) -> i64 {
    todo!("Compute LWE ciphertext noise level")
}

/// Exercise 6: Determine if LWE parameters are secure.
///
/// Security depends on n (dimension), q (modulus), and error distribution.
/// A rough guideline: n >= 256, q is prime, error is small relative to q.
///
/// Return true if parameters are likely secure, false if obviously insecure.
///
/// Insecure indicators:
/// - n < 64 (too small, brute-forceable)
/// - q < 2 (trivial modulus)
/// - error_bound >= q/2 (errors too large, decryption unreliable)
pub fn are_parameters_secure(n: usize, q: i64, error_bound: i64) -> bool {
    todo!("Evaluate LWE parameter security")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lwe_sample_basic() {
        let a = vec![3, 5, 7];
        let s = 2;
        let e = vec![1, 0, -1];
        let q = 11;
        let b = lwe_sample(&a, s, &e, q);
        // b[0] = (3*2 + 1) mod 11 = 7
        // b[1] = (5*2 + 0) mod 11 = 10
        // b[2] = (7*2 + (-1)) mod 11 = 13 mod 11 = 2
        assert_eq!(b, vec![7, 10, 2]);
    }

    #[test]
    fn test_verify_lwe_sample_valid() {
        let a = vec![3, 5, 7];
        let b = vec![7, 10, 2];
        let s = 2;
        let q = 11;
        assert!(verify_lwe_sample(&a, &b, s, q, 1));
    }

    #[test]
    fn test_verify_lwe_sample_invalid() {
        let a = vec![3, 5, 7];
        let b = vec![7, 10, 99]; // b[2] is way off
        let s = 2;
        let q = 11;
        assert!(!verify_lwe_sample(&a, &b, s, q, 1));
    }

    #[test]
    fn test_lwe_encrypt_decrypt_roundtrip() {
        // Tiny LWE instance for testing
        let a_matrix = vec![
            vec![1, 2],
            vec![3, 4],
            vec![5, 6],
            vec![7, 8],
        ];
        let s = vec![2, 3];
        let b: Vec<i64> = a_matrix.iter().map(|row| {
            let val: i64 = row.iter().zip(s.iter()).map(|(a, s)| a * s).sum();
            (val + 0) % 17 // no error for clean test
        }).collect();

        let subset = vec![0, 1, 2];
        let (u, v) = lwe_encrypt_bit(&a_matrix, &b, &subset, 0, 17);
        let decrypted = lwe_decrypt_bit(&u, &v, &s, 17);
        assert_eq!(decrypted, 0);
    }

    #[test]
    fn test_lwe_noise_level_zero() {
        // When everything is exact, noise should be 0
        let u = vec![1, 2];
        let s = vec![3, 4];
        // v = u . s = 1*3 + 2*4 = 11
        let v = 11;
        assert_eq!(lwe_noise_level(&u, v, &s, 17), 0);
    }

    #[test]
    fn test_lwe_noise_level_nonzero() {
        let u = vec![1, 2];
        let s = vec![3, 4];
        let v = 12; // noise = 12 - 11 = 1
        assert_eq!(lwe_noise_level(&u, v, &s, 17), 1);
    }

    #[test]
    fn test_parameters_secure_good() {
        assert!(are_parameters_secure(256, 7681, 3));
    }

    #[test]
    fn test_parameters_secure_too_small() {
        assert!(!are_parameters_secure(32, 7681, 3));
    }

    #[test]
    fn test_parameters_secure_bad_modulus() {
        assert!(!are_parameters_secure(256, 1, 3));
    }

    #[test]
    fn test_parameters_secure_error_too_large() {
        assert!(!are_parameters_secure(256, 100, 60));
    }
}
