#[cfg(not(feature = "solution"))]
pub mod p01_valid_palindrome;
#[cfg(feature = "solution")]
#[path = "solution/p01_valid_palindrome.rs"]
pub mod p01_valid_palindrome;
#[cfg(not(feature = "solution"))]
pub mod p02_two_sum_sorted;
#[cfg(feature = "solution")]
#[path = "solution/p02_two_sum_sorted.rs"]
pub mod p02_two_sum_sorted;
#[cfg(not(feature = "solution"))]
pub mod p03_three_sum;
#[cfg(feature = "solution")]
#[path = "solution/p03_three_sum.rs"]
pub mod p03_three_sum;
#[cfg(not(feature = "solution"))]
pub mod p04_container_most_water;
#[cfg(feature = "solution")]
#[path = "solution/p04_container_most_water.rs"]
pub mod p04_container_most_water;
#[cfg(not(feature = "solution"))]
pub mod p05_trapping_rain_water;
#[cfg(feature = "solution")]
#[path = "solution/p05_trapping_rain_water.rs"]
pub mod p05_trapping_rain_water;
