#[cfg(not(feature = "solution"))]
pub mod p01_binary_search;
#[cfg(feature = "solution")]
#[path = "solution/p01_binary_search.rs"]
pub mod p01_binary_search;
#[cfg(not(feature = "solution"))]
pub mod p02_search_matrix;
#[cfg(feature = "solution")]
#[path = "solution/p02_search_matrix.rs"]
pub mod p02_search_matrix;
#[cfg(not(feature = "solution"))]
pub mod p03_koko_eating_bananas;
#[cfg(feature = "solution")]
#[path = "solution/p03_koko_eating_bananas.rs"]
pub mod p03_koko_eating_bananas;
#[cfg(not(feature = "solution"))]
pub mod p04_find_min_rotated;
#[cfg(feature = "solution")]
#[path = "solution/p04_find_min_rotated.rs"]
pub mod p04_find_min_rotated;
#[cfg(not(feature = "solution"))]
pub mod p05_search_rotated;
#[cfg(feature = "solution")]
#[path = "solution/p05_search_rotated.rs"]
pub mod p05_search_rotated;
#[cfg(not(feature = "solution"))]
pub mod p06_time_map;
#[cfg(feature = "solution")]
#[path = "solution/p06_time_map.rs"]
pub mod p06_time_map;
