//! # Lesson 07: Build Provenance and SLSA Framework
//!
//! ## What is Build Provenance?
//!
//! Build provenance is a signed, tamper-proof record of how a software artifact
//! was built. It answers: **who built it, from what source, using which build system,
//! and when?**
//!
//! ## The SLSA Framework
//!
//! [SLSA](https://slsa.dev/) (Supply-chain Levels for Software Artifacts) defines
//! four levels of build integrity:
//!
//! | Level | Requirement | What It Prevents |
//! |-------|-------------|-----------------|
//! | 1 | Build process is documented | No protection |
//! | 2 | Provenance is generated by a hosted build service | Tampering with provenance |
//! | 3 | Build runs on a dedicated, auditable platform | Compromised build infra |
//! | 4 | Two-party review + hermetic, reproducible builds | Insider threats |
//!
//! ## Provenance Statement
//!
//! A provenance statement (in-toto format) contains:
//! - **Subject**: What was built (name + hash)
//! - **Builder**: Who/what built it (builder ID)
//! - **Recipe**: How it was built (steps, parameters)
//! - **Materials**: What inputs were used (source repo, deps)
//!
//! ## Attack: Build System Compromise
//!
//! An attacker gains access to the CI/CD system and modifies the build process
//! to inject a backdoor. Without provenance verification, the compromised binary
//! is indistinguishable from a legitimate one.
//!
//! ## Defense: Provenance Generation and Verification
//!
//! In this lesson, you will implement provenance data structures, generation,
//! and verification logic.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// A provenance statement in in-toto format.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceStatement {
    pub subject: Vec<Subject>,
    pub builder: Builder,
    pub recipe: Recipe,
    pub materials: Vec<Material>,
    pub metadata: ProvenanceMetadata,
}

/// The artifact that was built.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Subject {
    pub name: String,
    pub digest: DigestValue,
}

/// A hash digest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DigestValue {
    pub sha256: String,
}

/// Information about the build system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Builder {
    pub id: String,
}

/// The build recipe (how it was built).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Recipe {
    pub r#type: String,
    pub entry_point: String,
    pub arguments: Vec<String>,
}

/// An input material used in the build.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Material {
    pub uri: String,
    pub digest: DigestValue,
}

/// Metadata about the provenance itself.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProvenanceMetadata {
    pub build_started_on: String,
    pub build_finished_on: String,
    pub reproducible: bool,
    pub completeness: Completeness,
}

/// Completeness indicators for the provenance.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Completeness {
    pub parameters: bool,
    pub environment: bool,
    pub materials: bool,
}

/// SLSA security level.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub enum SlsaLevel {
    None = 0,
    Level1 = 1,
    Level2 = 2,
    Level3 = 3,
    Level4 = 4,
}

/// Exercise 1: Compute SHA-256 of build output for the subject digest.
///
/// Return a lowercase hex string.
///
/// Hints:
/// - Use `Sha256` from `sha2`
/// - Feed the output bytes, finalize, hex-encode
pub fn compute_artifact_hash(artifact: &[u8]) -> String {
    todo!("Compute SHA-256 hash of build artifact")
}

/// Exercise 2: Create a ProvenanceStatement for a build.
///
/// Given the artifact name, artifact bytes, source URI, builder ID,
/// and build timestamps, construct a complete provenance statement.
///
/// Hints:
/// - Use `compute_artifact_hash` for the subject digest
/// - Set completeness to all-true for this exercise
/// - Use standard recipe type "https://slsa.dev/provenance/v1"
pub fn create_provenance(
    artifact_name: &str,
    artifact: &[u8],
    source_uri: &str,
    source_hash: &str,
    builder_id: &str,
    entry_point: &str,
    started_on: &str,
    finished_on: &str,
) -> ProvenanceStatement {
    todo!("Create a complete provenance statement")
}

/// Exercise 3: Evaluate the SLSA level of a provenance statement.
///
/// Criteria:
/// - Level 1: Has a builder ID (non-empty)
/// - Level 2: Level 1 + materials list is non-empty + build timestamps are set
/// - Level 3: Level 2 + completeness is all-true + reproducible is true
/// - Level 4: Level 3 + two materials (source + dependency provenance)
///
/// Hints:
/// - Check each level's criteria in order (highest first)
/// - Return the highest level that qualifies
pub fn evaluate_slsa_level(provenance: &ProvenanceStatement) -> SlsaLevel {
    todo!("Evaluate SLSA compliance level")
}

/// Exercise 4: Verify that a build artifact matches the subject in provenance.
///
/// Compute the hash of the artifact and compare it with the subject's digest.
/// Return true if they match.
///
/// Hints:
/// - Hash the artifact with `compute_artifact_hash`
/// - Compare with `provenance.subject[0].digest.sha256`
pub fn verify_artifact(
    artifact: &[u8],
    provenance: &ProvenanceStatement,
) -> bool {
    todo!("Verify artifact matches provenance subject")
}

/// Exercise 5: Serialize provenance to JSON.
///
/// Hints:
/// - Use `serde_json::to_string_pretty`
pub fn serialize_provenance(provenance: &ProvenanceStatement) -> String {
    todo!("Serialize provenance to JSON")
}

/// Exercise 6: Deserialize provenance from JSON.
///
/// Hints:
/// - Use `serde_json::from_str`
pub fn deserialize_provenance(json: &str) -> Option<ProvenanceStatement> {
    todo!("Deserialize provenance from JSON")
}

/// Exercise 7: Generate a provenance summary report.
///
/// Format:
/// ```text
/// PROVENANCE REPORT
/// Subject: {name} (sha256:{hash_prefix}...)
/// Builder: {builder_id}
/// SLSA Level: {level}
/// Materials: {count} input(s)
/// Reproducible: {yes/no}
/// ```
///
/// Use first 12 chars of hash as prefix.
pub fn provenance_report(provenance: &ProvenanceStatement) -> String {
    todo!("Generate provenance summary report")
}

/// Exercise 8: Validate provenance completeness.
///
/// Return a list of missing/incomplete fields:
/// - Subject name or hash is empty
/// - Builder ID is empty
/// - No materials listed
/// - Timestamps are empty
pub fn validate_provenance(provenance: &ProvenanceStatement) -> Vec<String> {
    todo!("Validate provenance completeness")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_provenance() -> ProvenanceStatement {
        ProvenanceStatement {
            subject: vec![Subject {
                name: "my-app".to_string(),
                digest: DigestValue {
                    sha256: compute_artifact_hash(b"binary content"),
                },
            }],
            builder: Builder {
                id: "https://github.com/actions/runner".to_string(),
            },
            recipe: Recipe {
                r#type: "https://slsa.dev/provenance/v1".to_string(),
                entry_point: "build.sh".to_string(),
                arguments: vec!["--release".to_string()],
            },
            materials: vec![
                Material {
                    uri: "https://github.com/org/repo".to_string(),
                    digest: DigestValue {
                        sha256: "abc123".to_string(),
                    },
                },
            ],
            metadata: ProvenanceMetadata {
                build_started_on: "2024-01-01T00:00:00Z".to_string(),
                build_finished_on: "2024-01-01T00:05:00Z".to_string(),
                reproducible: true,
                completeness: Completeness {
                    parameters: true,
                    environment: true,
                    materials: true,
                },
            },
        }
    }

    #[test]
    fn test_compute_artifact_hash() {
        let hash = compute_artifact_hash(b"test binary");
        assert_eq!(hash.len(), 64);
        assert_eq!(hash, compute_artifact_hash(b"test binary"));
    }

    #[test]
    fn test_create_provenance() {
        let prov = create_provenance(
            "my-app",
            b"binary",
            "https://github.com/org/repo",
            "src123",
            "https://github.com/actions/runner",
            "build.sh",
            "2024-01-01T00:00:00Z",
            "2024-01-01T00:05:00Z",
        );
        assert_eq!(prov.subject.len(), 1);
        assert_eq!(prov.subject[0].name, "my-app");
        assert_eq!(prov.builder.id, "https://github.com/actions/runner");
        assert_eq!(prov.materials.len(), 1);
    }

    #[test]
    fn test_evaluate_slsa_level_none() {
        let mut prov = sample_provenance();
        prov.builder.id = String::new();
        assert_eq!(evaluate_slsa_level(&prov), SlsaLevel::None);
    }

    #[test]
    fn test_evaluate_slsa_level2() {
        let mut prov = sample_provenance();
        // Meets Level 2 but not Level 3 (reproducible = false)
        prov.metadata.reproducible = false;
        assert!(evaluate_slsa_level(&prov) >= SlsaLevel::Level2);
    }

    #[test]
    fn test_evaluate_slsa_level3() {
        let prov = sample_provenance();
        assert!(evaluate_slsa_level(&prov) >= SlsaLevel::Level3);
    }

    #[test]
    fn test_evaluate_slsa_level4() {
        let mut prov = sample_provenance();
        // Add second material for Level 4
        prov.materials.push(Material {
            uri: "https://github.com/org/dep-provenance".to_string(),
            digest: DigestValue { sha256: "dep456".to_string() },
        });
        assert_eq!(evaluate_slsa_level(&prov), SlsaLevel::Level4);
    }

    #[test]
    fn test_verify_artifact_match() {
        let prov = sample_provenance();
        assert!(verify_artifact(b"binary content", &prov));
    }

    #[test]
    fn test_verify_artifact_mismatch() {
        let prov = sample_provenance();
        assert!(!verify_artifact(b"tampered content", &prov));
    }

    #[test]
    fn test_provenance_roundtrip() {
        let prov = sample_provenance();
        let json = serialize_provenance(&prov);
        let restored = deserialize_provenance(&json).unwrap();
        assert_eq!(restored.subject[0].name, prov.subject[0].name);
        assert_eq!(restored.builder.id, prov.builder.id);
    }

    #[test]
    fn test_provenance_report_format() {
        let prov = sample_provenance();
        let report = provenance_report(&prov);
        assert!(report.contains("PROVENANCE REPORT"));
        assert!(report.contains("my-app"));
        assert!(report.contains("SLSA Level"));
    }

    #[test]
    fn test_validate_provenance_valid() {
        let prov = sample_provenance();
        let issues = validate_provenance(&prov);
        assert!(issues.is_empty());
    }

    #[test]
    fn test_validate_provenance_missing_builder() {
        let mut prov = sample_provenance();
        prov.builder.id = String::new();
        let issues = validate_provenance(&prov);
        assert!(!issues.is_empty());
        assert!(issues.iter().any(|i| i.to_lowercase().contains("builder")));
    }
}
