#[cfg(not(feature = "solution"))]
pub mod p01_number_of_islands;
#[cfg(feature = "solution")]
#[path = "solution/p01_number_of_islands.rs"]
pub mod p01_number_of_islands;
#[cfg(not(feature = "solution"))]
pub mod p02_clone_graph;
#[cfg(feature = "solution")]
#[path = "solution/p02_clone_graph.rs"]
pub mod p02_clone_graph;
#[cfg(not(feature = "solution"))]
pub mod p03_max_area_island;
#[cfg(feature = "solution")]
#[path = "solution/p03_max_area_island.rs"]
pub mod p03_max_area_island;
#[cfg(not(feature = "solution"))]
pub mod p04_pacific_atlantic;
#[cfg(feature = "solution")]
#[path = "solution/p04_pacific_atlantic.rs"]
pub mod p04_pacific_atlantic;
#[cfg(not(feature = "solution"))]
pub mod p05_course_schedule;
#[cfg(feature = "solution")]
#[path = "solution/p05_course_schedule.rs"]
pub mod p05_course_schedule;
#[cfg(not(feature = "solution"))]
pub mod p06_course_schedule_ii;
#[cfg(feature = "solution")]
#[path = "solution/p06_course_schedule_ii.rs"]
pub mod p06_course_schedule_ii;
#[cfg(not(feature = "solution"))]
pub mod p07_graph_valid_tree;
#[cfg(feature = "solution")]
#[path = "solution/p07_graph_valid_tree.rs"]
pub mod p07_graph_valid_tree;
#[cfg(not(feature = "solution"))]
pub mod p08_connected_components;
#[cfg(feature = "solution")]
#[path = "solution/p08_connected_components.rs"]
pub mod p08_connected_components;
#[cfg(not(feature = "solution"))]
pub mod p09_rotting_oranges;
#[cfg(feature = "solution")]
#[path = "solution/p09_rotting_oranges.rs"]
pub mod p09_rotting_oranges;
