#[cfg(not(feature = "solution"))]
pub mod p01_daily_temperatures;
#[cfg(feature = "solution")]
#[path = "solution/p01_daily_temperatures.rs"]
pub mod p01_daily_temperatures;
#[cfg(not(feature = "solution"))]
pub mod p02_next_greater_element;
#[cfg(feature = "solution")]
#[path = "solution/p02_next_greater_element.rs"]
pub mod p02_next_greater_element;
#[cfg(not(feature = "solution"))]
pub mod p03_stock_span;
#[cfg(feature = "solution")]
#[path = "solution/p03_stock_span.rs"]
pub mod p03_stock_span;
#[cfg(not(feature = "solution"))]
pub mod p04_histogram_max_area;
#[cfg(feature = "solution")]
#[path = "solution/p04_histogram_max_area.rs"]
pub mod p04_histogram_max_area;
